### ISSUE TITLE
 Invariant Violation: requireNativeComponent: "RNCAndroidDialogPicker" was not found in the UIManager.

### ISSUE THREAD

**Issue by prateekpareek** [uraway/react-native-simple-time-picker#14]
I am getting this error when I am doing the same steps as you describe in your documents .please improve your documents

**Comment by uraway** [comment]
Try https://github.com/react-native-picker/picker/issues/136#issuecomment-709077127

**Comment by prateekpareek** [comment]
sorry but this does not solve my issue
