### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by phamhoaivu911** [uraway/react-native-simple-time-picker#15]
Thanks, @uraway for a great library.

Currently, the picker does not work well in dark mode. The text color is supposed to be white instead of black.

<img width="341" alt="Screen Shot 2021-03-03 at 22 23 31" src="https://user-images.githubusercontent.com/4929170/109828335-1e824500-7c6f-11eb-82a4-515694419671.png">|<img width="345" alt="Screen Shot 2021-03-03 at 22 22 32" src="https://user-images.githubusercontent.com/4929170/109828361-2346f900-7c6f-11eb-84c9-f7fe28430c1f.png">
:-:|:-:
Light mode | Dark mode

Do you have a plan to support dark mode?

**Comment by phamhoaivu911** [comment]
To make it simple, I suggest we add one more prop: `textColor` to the TimePicker. It will support customizing the color of the `Picker.Item`'s label in general.

Then we can check the current `colorScheme` and pass the correct `textColor` to it.

**Comment by uraway** [comment]
Thanks, I will do it this weekend. but pull requests are welcomed

**Comment by phamhoaivu911** [comment]
Hi @uraway, please help me review this PR #17 
Thank you.

**Comment by uraway** [comment]
Thanks, @phamhoaivu911
I just published v1.2.0 
https://snack.expo.io/@uraway/react-native-simple-time-picker

**Comment by phamhoaivu911** [comment]
Thanks @uraway 🎉
