### ISSUE TITLE
Selectors are not working on android

### ISSUE THREAD

**Issue by ameliacode** [uraway/react-native-simple-time-picker#173]
Hi, I think there is some problem with your android version
Down below is my package.json

    "@react-native-picker/picker": "^1.16.3",
    "react-native-simple-time-picker": "^1.3.7",
    "react-native": "^0.64.2",
 
I've followed one of your react native sample ,however, selector does not work properly 
and also hour and minute variables present like this:
![image](https://user-images.githubusercontent.com/26244569/130466150-5f7d291f-074e-464e-914a-a6075ee40c44.png)

  `   <TimePicker 
                            value = {{startHours, startMinutes}} 
                            onChange={handleStartTime}
                            minutesInterval={15}
                            zeroPadding={true}
                            />     
`

**Comment by uraway** [comment]
`value` accepts only `{ hours: number, minutes: number }`

Your code should be like this `<TimePicker value={{ hours: startHours, minutes: startMinutes }} ...`
