### ISSUE TITLE
Getting this error ExceptionsManager.js:179 Invariant Violation: requireNativeComponent: "RNCPicker" was not found in the UIManager

### ISSUE THREAD

**Issue by IshaTyagi** [uraway/react-native-simple-time-picker#50]
Using   "react-native-simple-time-picker": "^1.3.0",
"@react-native-picker/picker": "^1.14.0",

**Comment by uraway** [comment]
Please describe in detail to reproduce the bug.
Maybe you didnt sync dependencies. Try `npx react-native run-android` after installation.

**Comment by Seanmclem** [comment]
Yeah I had this exact issue. It was because I didn't stop and restart the app when I was installing it. I just left it running. So after stopping the instance of the running app, and re-running `react-native run-ios`, it worked. Thanks!

**Comment by Seanmclem** [comment]
I had to restart my react native instance, but that didn't really help until I also restarted the simulator. I also uninstalled the app first before it reinstalled it. Idk which part was important, but it worked after
