### ISSUE TITLE
TimePicker in Android not Working

### ISSUE THREAD

**Issue by DFRZ7** [uraway/react-native-simple-time-picker#94]
Hi, 
I was working with the TimePicker before, and it was wokring fine on Android. 
But with this version:

"@react-native-picker/picker": "^1.14.0",
"react-native-simple-time-picker": "^1.3.0",

On android I'm not able to make it work, it simply does not show any selector. 

iOS is working perfectly. 

Would really appreciate any input, since this component is incredible for our project. Thank you, regards.

**Comment by uraway** [comment]
Hi, can you share error logs to investigate?

FYI, deps of these versions work fine
```
{
  "dependencies": {
    "@react-native-picker/picker": "1.9.2",
    "react-native-simple-time-picker": "1.3.0"
  }
}
```

https://snack.expo.io/@uraway/react-native-simple-time-picker

**Comment by DFRZ7** [comment]
Hi, and thank you!

So we tried 1.9.2 / 1.9.6 for the react native picker version, but as soon as the app loaded in Android, we get an error:
Unable to resolve ./AndroidDropdownPickerNativeComponent from node_modules/@react-native-picker/picker/js/PickerAndroid.android.js

Now, with the versions I mentioned at the begining, did not get any error. 
Is just as if the drop down is not working. Kind of like we can see the down arrow showing, but if i try to touch it, it simply does not do anything. But if you need any additional detail, please do let me know, and thank you!

**Comment by uraway** [comment]
Are you using expo v41+? I found that expo SDK v41 expects  `@react-native-picker/picker`  v1.9.11

Also, I confirmed `@react-native-picker/picker` v1.14.0 does not work on expo SDK v41

![image](https://user-images.githubusercontent.com/15242484/120916275-aac75c80-c6e3-11eb-89f6-2f07216ffe1a.png)

**Comment by DFRZ7** [comment]
Hi, I'm using if not mistaken: "expo-cli 4.0.17"
I tested the picker version you mentioned, but still the same issue unfortunatelly.

**Comment by uraway** [comment]
I think `expo-cli` is not relevant to Expo SDK version.  Can you share your `package.json` or a repository to reproduce the bug?

**Comment by link82** [comment]
> Hi, can you share error logs to investigate?
> 
> FYI, deps of these versions work fine
> 
> ```
> {
>   "dependencies": {
>     "@react-native-picker/picker": "1.9.2",
>     "react-native-simple-time-picker": "1.3.0"
>   }
> }
> ```
> 
> https://snack.expo.io/@uraway/react-native-simple-time-picker

I was facing the same issue version 1.3.3 of react-native-simple-time-picker but after downgrading to version 1.3.0 it started working on Android too. (I'm using version 2.2.1 of @react-native-picker/picker)

PS: if you can't see dropdown icons on Android just use `dropdownIconColor` prop

**Comment by DFRZ7** [comment]
Hi All, I apologize for replying so late. We managed to get it working, thank you so much, it was a mistake on my end. Excellent component! Regards.
